### PR TITLE
Made pybnn and torch optional

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by aaronkl** [comment]
Would you mind explaining why pybnn should be optional?

**Comment by KOLANICH** [comment]
Because it is used only in wrapper_bohamiann.py. The rest of the lib doesn't need that. And these are dependencies, some prefer not to have on own machines, because it is too costly to build and/or keep them.

**Comment by KOLANICH** [comment]
@aaronkl

**Comment by aaronkl** [comment]
one of the key components of RoBO compared to other BO packages is that it support Bayesian neural networks (e.g Bohamiann and DNGO) which  are implemented in the pybnn package. So I don't see why we should make that optional. For instance, it is also needed in the central [fmin](https://github.com/automl/RoBO/blob/master/robo/fmin/bayesian_optimization.py) and [mtbo](https://github.com/automl/RoBO/blob/master/robo/fmin/warmstart_mtbo.py) interface

**Comment by KOLANICH** [comment]
No, it is not needed. Some parts are fully useful without pytorch. I had to patch the lib and I don't think it is a right solution.

**Pull request closed without merging**
